### ISSUE TITLE
Jobs added during runtime do not run 

### ISSUE THREAD

**Issue by IvaTutis** [NCronJob-Dev/NCronJob#100]
## Bug description
The Job will be triggered at the expected time if it is added to the runtime registry at the start of the application. 
When the job is added later to the registry using the same service, it will appear in the registry (breakpoint view) as it should, but will not be triggered at the expected time. 

The instant job registration and execution works fine. 

The jobs below are added and deleted from the registries in the same manner as in the documentation and other issues.  (referencing [issue](https://github.com/NCronJob-Dev/NCronJob/issues/83) and [docs](https://docs.ncronjob.dev/advanced/dynamic-job-control))

## Context
I am making a task scheduler, and am using NCronJob as an alternative to Quartz. During runtime, I want to have the user define a job that is triggered on a defined, repeating schedule. 
The jobs that are allready defined in the database are added to the registry using a hosted service during runtime, after startup.
These jobs are can be removed and new jobs can be added through the runtime registry.  
We did not make an interface for an update at this time

### Task

In the example provided below, one task can have N triggers, where every trigger will equate one job registered during runtime.
When unregistering a task, all related jobs will be unregistered.

### Custom Interface for job registries 

All the additions and deletions of jobsfrom the registry are done through the same service, which shows the same behaviour both as a transient and a singleton: [service example](https://gist.github.com/IvaTutis/0358c46c165f3b90b88409fc55a381c2)
 
```mermaid
classDiagram
    class IJobRegistrationService {
        <<interface>>
        +RegisterOneTimeJob(AutomatedTask task) Task
        +UpsertRecurringJobRegistration(AutomatedTask task) Task
        +TryUnregisteringRecurringJob(Guid taskId) Task
    }

    class JobRegistrationService {
        -IRuntimeJobRegistry _jobRegistry
        -IInstantJobRegistry _instantJobRegistry
        -ILogger<JobRegistrationService> _logger
        -Func<Guid, Guid, string> JobName
        -Func<Guid> ManualJobTriggerId
        +RegisterOneTimeJob(AutomatedTask task) Task
        +UpsertRecurringJobRegistration(AutomatedTask task) Task
        +TryUnregisteringRecurringJob(Guid taskId) Task
        -RegisterJobWithSingleTrigger(Guid taskId, PeriodicallyTrigger trigger) void
        -DeleteAllJobsForTask(Guid taskId) void
        -IsJobRelatedToAutomatedTask(RecurringJobSchedule job, Guid taskId) bool
    }

    class IRuntimeJobRegistry {
        <<interface>>
    }

    class IInstantJobRegistry {
        <<interface>>
    }

    class ILogger {
        <<interface>>
    }

    JobRegistrationService ..|> IJobRegistrationService
    JobRegistrationService --> IRuntimeJobRegistry
    JobRegistrationService --> IInstantJobRegistry
    JobRegistrationService --> ILogger
```

## Expected behavior
The jobs will run at the expected time regardless of how they were registered (given they are well formed and saved in the registry)

##  Version information
 - NCronJobVersion: 3.1.3.
 - .NET runtime version: 8.0
 - Framework: Blazor

**Comment by linkdotnet** [comment]
Hey @IvaTutis,

thanks for raising the issue. Do you have a reproducible example by any chance?.

I tried a very minimal setup:
```csharp
using NCronJob;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddNCronJob();

var app = builder.Build();

app.MapGet("/", (IRuntimeJobRegistry registry) =>
{
    registry.AddJob(j => j.AddJob(() => { Console.WriteLine("HEY"); }, "* * * * * *"));
});

app.Run();
```

If you hit the "/" endpoint with a browser you will see "HEY" every second on the console. So jobs are executed.

**Comment by IvaTutis** [comment]
Hey @linkdotnet 

Sorry for the late reply. 
I created a small Blazor app ](https://github.com/IvaTutis/NChronJobBugExample/tree/main) to showcase the bug in a repeatable enviroment.

All of the jobs that are added to the RuntimeRegistry here are added in the same manner, and they appear in the registry when added (and I can wipe them from it well). 

The main issue is that only the ones that are added >>RIGHT AFTER STARTUP via TaskSyncService<< seem to work. 
The ones added via the UI seem to not fire. 

The example you provice above with ` app.MapGet` would therefore technically fit the first case.

**Comment by linkdotnet** [comment]
New version (currently preview): https://www.nuget.org/packages/NCronJob/3.3.1-preview

It would be great if you can report back, whether or not that fixes your case.
Thanks.

**Comment by IvaTutis** [comment]
Tested on my projects, runtime jobs now fire as expected. 
Will update on a different issue if anything else pops up.

Thank you for the fix, and great work! 🐛 ✨
