### ISSUE TITLE
Multiple AddNCronJob only registers ones

### ISSUE THREAD

**Issue by skarum** [NCronJob-Dev/NCronJob#138]
**Describe the bug**
Prior to version 3.3.3 you could register multiple jobs by calling `AddNCronJob` multiple times.

If I had a setup like this:

```csharp
services.AddNCronJob(
    builder => builder
        .AddJob<TestJob1>(o => o.WithCronExpression("0/1 * * * * *"))
);

services.AddNCronJob(
    builder => builder
        .AddJob<TestJob2>(o => o.WithCronExpression("0/1 * * * * *"))
);
```

**Current behavior**
Only `TestJob1` is executed

**Expected behavior**
Both `TestJob1` and `TestJob2` should be executed

**Version information**
 - NCronJobVersion: 3.3.3-5
 - .NET runtime version: 8 and 9

I think the change from `builder.RegisterJobs();` to  `services.TryAddSingleton(jobRegistry);` in this commit is the cause of this behavior, but I'm not sure if it's intentional or a bug?

If this is intentional I think the second call to `.AddNCronJob(...` should throw an exception.

**Comment by linkdotnet** [comment]
Hey @skarum 

No that is absolutely not intentional (at least until now :D) and should be fixed! Thanks for the report!

**Comment by skarum** [comment]
Ohh -  can see I forgot to link  to the commit: https://github.com/NCronJob-Dev/NCronJob/commit/0fe7e6666d074b2c83ce0fccc679b349a1a7f41d#diff-997ac4e971e8a1108f07128317dfa5a16164555c9220704a45a2d7f26ff01eb0

**Comment by linkdotnet** [comment]
As a workaround, you can "just" have one call:
```csharp
services.AddNCronJob(
    builder => builder
        .AddJob<TestJob1>(o => o.WithCronExpression("0/1 * * * * *"))
        .AddJob<TestJob2>(...)
);
```

**Comment by linkdotnet** [comment]
@nulltoken we might wanna change that in the future to remove ambiguity (and make our code simpler)

**Comment by skarum** [comment]
> As a workaround, you can "just" have one call:
> 
> ```cs
> services.AddNCronJob(
>     builder => builder
>         .AddJob<TestJob1>(o => o.WithCronExpression("0/1 * * * * *"))
>         .AddJob<TestJob2>(...)
> );
> ```

Thanks, that could work. 

Unfortunately I have decentralized my setup, where different parts of my code can just add stuff to the IOC container, including registering a job. 

So, If you are going to fix it so it'll work in old way I'll just wait for the next release. If not I'll adjust my code. :-)

**Comment by linkdotnet** [comment]
I think I have a fix - which I will push as a preview in a few minutes

**Comment by linkdotnet** [comment]
A new `3.3.7-preview` package will be available in a few minutes. Thanks for the report
