### ISSUE TITLE
`CancelledJobIsStillAValidExecution` is not deterministic

### ISSUE THREAD

**Issue by linkdotnet** [NCronJob-Dev/NCronJob#34]
The following test is flaky and has to be fixed: `CancelledJobIsStillAValidExecution`.
The problem is that this test seems to fail only when executed with other tests.

EDIT:
The test utilizes a `Task.Delay(200)` to reduce flakiness. The only way to tackle this properly is to introduce some kind of notification layer so that the test has a chance to know when certain operations are done.

**Comment by linkdotnet** [comment]
I can repeatedly make it fail if I run `JobShouldHonorApplicationCancellationDuringRetry` first and then `CancelledJobIsStillAValidExecution`

**Comment by falvarez1** [comment]
[PR-85](https://github.com/NCronJob-Dev/NCronJob/pull/85) fixes this issue
