### ISSUE TITLE
Remove `enableSecondPrecision`

### ISSUE THREAD

**Issue by linkdotnet** [NCronJob-Dev/NCronJob#44]
The `enableSecondPrecision` flag is no longer needed since we automatically determine whether or not we want that precision.

So, there is no benefit for the user. While this is a major breaking change, I am still inclined to say it is fine to do in `v2`.

**Comment by kunalshokeen051** [comment]
Hi, can i work on this issue.

**Comment by linkdotnet** [comment]
Hey @kunalshokeen051  - thanks for offering your help. Sure thing! 
If you have any questions, feel free to let us know.

By the way @falvarez1  - do you see any reason against removing the flag and releasing it in `v2`?

**Comment by falvarez1** [comment]
No problems. After adding the automatic detection the only reason for keeping it is backwards compatibility. We just need to document as a breaking change.

**Comment by linkdotnet** [comment]
Yeah, that said, @kunalshokeen051 feel free to make the changes.
You might want to add an entry about the migration to the docs. Basically telling folks that they don't need that entry as it is automatically inferred.

**Comment by linkdotnet** [comment]
Given that there was no response for 2 weeks I will unassign the ticket so anyone who wants to help, can do so.

**Comment by linkdotnet** [comment]
Done on `v3`
