### ISSUE TITLE
Allow bypass concurrency requirements for instant jobs

### ISSUE THREAD

**Issue by linkdotnet** [NCronJob-Dev/NCronJob#65]
Follow-up to #61 and the discussion.

## Motivation
Basically, users might want to be able to trigger a job and be sure that this job gets executed independent of whether or not the concurrency requirement is met.

So if we have a job that allows only one run at a time and there is a job running, we still want to be able to say: "Hey I don't care about those requirements, execute that job anyway!".

**Comment by falvarez1** [comment]
This is being handled in [PR-85](https://github.com/NCronJob-Dev/NCronJob/pull/85)
https://github.com/NCronJob-Dev/NCronJob/blob/6f9d15d3a41caf5171d979096ef3b8e8c7facd57/src/NCronJob/Registry/IInstantJobRegistry.cs#L156-L159

It bypasses the Queues altogether for an _instant execution_ without _scheduling_ to run.
