### ISSUE TITLE
Runtime modification of scheduled jobs

### ISSUE THREAD

**Issue by KorsG** [NCronJob-Dev/NCronJob#83]
**Is your feature request related to a problem? Please describe.**
In the process of examining the possibility to use this library as a replacement for Hangfire in many of our solutions, we miss the option to do runtime modifications of the scheduled jobs. 

In our current setup we have bound job config to the "IConfiguration" system, so its possible to edit e.g. an appsettings.json file with options like CronExpression, Enabled/Disabled, Timezone etc., for each job, which automatically reloads during runtime and adds, updates, removes the job to the Hangfire scheduler, without having to restart the host (win-service), which can be very cumbersome in many on-prem deployments. 

With this option the job config could be loaded from a remote path/url/database and automatically be applied.

**Describe the solution you'd like**
A way to add/update/remove scheduled jobs at runtime. Possibly via (I)JobRegistry. We would need to fetch a specific JobDefinition via its JobName, so it should also be possible to provide a "custom" JobName when registering Jobs.

**Describe alternatives you've considered**
None

**Additional context**
None

Let me know if I can provide further details 😊

**Comment by linkdotnet** [comment]
Thanks for the idea!

Given a job that has multiple CRON expressions, would you like to control every single of them or just all of them?
So given something like:
```csharp
Services.AddNCronJob(p => p.AddJob<MyJob>(j => j.WithCronExpression("1 0 * * *).And.WithCronExpression("11 1 * * * ")));
```

Would you like to be able to update/remove all of them together or one by one?

On top of my head, we can "ask" for a jobname - internally we already have something like that, so it is a matter of exposing.
If a JobName is not set, we automatically use the typename.

That said, we might want to offer something like this:
```csharp
public interface IJobRegistry
{
  public void EnableJob(string jobName); // Important for anonymous jobs as well
  public void EnableJob<TJob>() where TJob : IJob;
  public void EnableJob(Type jobType);

  public void DisableJob(string jobName); // Important for anonymous jobs as well
  public void DisableJob<TJob>() where TJob : IJob;
  public void DisableJob(Type jobType);

  public void AddJob(Action<NCronJobOptionBuilder> builder);

  public void RemoveJob(string jobName);
  public void RemoveJob<TJob>() where TJob : IJob;
  public void RemoveJob(Type jobType);
}
```

I am not sure what exactly the use case for updating would be? Do you want to change the name/CRON expression at runtime?

That brings me to another point: The code should be the single source of truth - so after restarting the service, we are back to square one. So whatever is written inside your `builder.Services.AddNCronJob(...)` is the truth.

**Comment by linkdotnet** [comment]
Another "limitation" that comes to my mind, when you want to add jobs dynamically (if they derive from `IJob`): They have to live inside the container, so that we can resolve dependencies.

With our minimal API, that isn't a requirement, as we resolve the delegate at runtime anyway.

**Comment by KorsG** [comment]
Hi Steven and thank you so much for looking into this - truly awesome! 😎

1 
--
> Given a job that has multiple CRON expressions, would you like to control every single of them or just all of them? So given something like:

> 
> ```cs
> Services.AddNCronJob(p => p.AddJob<MyJob>(j => j.WithCronExpression("1 0 * * *).And.WithCronExpression("11 1 * * * ")));
> ```
> 
> Would you like to be able to update/remove all of them together or one by one?

I would like to control each one, but I feel that's solved by the new `IRuntimeJobRegistry`.

2
--
> I am not sure what exactly the use case for updating would be? Do you want to change the name/CRON expression at runtime?

Yes, our main use-case for this is actually changing the CRON expression at runtime. To disable jobs in our current Hangfire solution we actually just use the following "Never" CRON "* * 31 2 *", which is valid, but never fires because its the 31st of February.

3
--
> My question would be: Do you need Disable / Enable on said interface? And further: Do you need to disable jobs inside AddNCronJob? Or broader: What would the gap be?

I don't think we will need a specific Enable/Disable method as we can just the the "Never" CRON, which also makes it possible to add "disabled" jobs inside AddNCronJob if needed.

4
--

> Maybe we could add something like:

> ```cs
> UpdateJob(string job, Action<UpdateBuilder> update);
> // Alternatively
> UpdateJob(string job, string cronExpression); // Is by job name enough?
> UpdateJob(string job, object? parameter);
> ```

Currently we only need to be able to update the CRON so `UpdateJob(string job, string cronExpression);` would be enough as an MVP in our case - maybe with a TimeZone overload. I feel that the UpdateBuilder could be a great addition at a later point if needed - maybe it could even support updating multiple CRON expressions/JobOptions. 

We could of course just remove and re-add the jobs instead of updating, but in most cases we actually register all jobs in startup to "define" the jobs with Notification handlers etc., so its much "easier" to just change the CRON instead of removing/adding the whole job definition. 

5
--
I would also like to request the option to iterate (CRON) jobs in the `IRuntimeJobRegistry`, because when the "config" changes, we want to iterate jobs in the registry and remove any that may have been removed from the config. 
That would also be beneficial for diagnostics and simple UI scenarios.

6
--
I also found the need for an overload in the NCronJobOptionsBuilder when adding jobs via the JobOptionBuilder:
currently there is this:
`public IStartupStage<T> AddJob<T>(Action<JobOptionBuilder>? options = null)`
but I need the following because I am constructing my own options based on config:
`public IStartupStage<T> AddJob<T>(JobOptionBuilder options)`
 
It's not a must, but would definitely help.


---

Let me know what you think and thanks again!

**Comment by linkdotnet** [comment]
Good points overall. I do think many of them are achievable. I am inclined to release a small preview-release from the feature branch for you to get your hands on to gather some further insights. Let me know if this would workout for you.

To your fifth point: Allowing to iterate over Cron jobs. I am a bit reluctant to expose our internal model, as that binds us to keep it stable. That said, what would be a minimal version for you to work with?

For example something along the line like:
```csharp
string? GetCronExpression(string jobName);
// Or something like this
(string? CronExpression, TimeZoneInfo? timeZone) GetCronExpression(string jobName);
```

Regarding number 6: `public IStartupStage<T> AddJob<T>(JobOptionBuilder options)`.
While `JobOptionBuilder` is public a lot of things aren't. Well you could still chain it like inside the action - my question is what scenario is easier or which scenario would enable you that API surface?

**Comment by linkdotnet** [comment]
Another assumption I have and maybe you could challenge me here:
Job names have to be unique. That said: Adding two jobs with the same name should raise an exception.

**Comment by KorsG** [comment]
Looks great! 👍

1
--
> To your fifth point: Allowing to iterate over Cron jobs. I am a bit reluctant to expose our internal model, as that binds us to keep it stable. That said, what would be a minimal version for you to work with?

I understand the increased complexity about having to expose this, but maybe it could just be a very simple representation to begin with? 

I created a branch to give the latest changes a spin where I created a simple GetJobs method in the `RuntimeJobRegistry` and a simple usage example:

Usage: https://github.com/KorsG/NCronJob/blob/cb6b58eba6eb4493429d00d1015a9693ae488bf3/sample/DynamicSample/ScheduledJobsService.cs#L51

Implementation: https://github.com/KorsG/NCronJob/blob/cb6b58eba6eb4493429d00d1015a9693ae488bf3/src/NCronJob/Registry/RuntimeJobRegistry.cs#L177

It only returns the most basic info, and should probably return a type instead of a tuple - maybe `RuntimeJob`?

The only "issue" I currently see with it, is that it returns the Cronos parsed CronExpression and not the "input" CronExpression, which makes it difficult to do a comparison, to check if it has changed:
https://github.com/KorsG/NCronJob/blob/cb6b58eba6eb4493429d00d1015a9693ae488bf3/sample/DynamicSample/ScheduledJobsService.cs#L58

If you agree, we could store the "input" Cron in the JobDefinition alongside the Cronos parsed version, and the return the "input" Cron instead?

2
--
> Another assumption I have and maybe you could challenge me here:
> Job names have to be unique. That said: Adding two jobs with the same name should raise an exception.
> 
> The alternative is more like a "tag" where this doesn't have to be unique, but calling something like RemoveJob("Foo") and Foo is mapped to multiple jobs will delete all of them.
> 
> I don't want to prime anyone, but I am much in favor of having a unique job name and throw an exception if that isn't the case.

I agree 100% and are also in favor of unique JobNames 👍


3
--
> Regarding number 6: public IStartupStage<T> AddJob<T>(JobOptionBuilder options).
> While JobOptionBuilder is public a lot of things aren't. Well you could still chain it like inside the action - my question is what scenario is easier or which scenario would enable you that API surface?

I have a small scenario here:
https://github.com/KorsG/NCronJob/blob/cb6b58eba6eb4493429d00d1015a9693ae488bf3/sample/DynamicSample/ScheduledJobsConfigurationExtensions.cs#L46

But its easily achievable without the overload, so you can just disregard the request 🙂

**Comment by linkdotnet** [comment]
We could offer a `GetAllSchedules` method that returns basically those 3 information:
 1. Job Name (if any is present)
 2. Cron Schedule
 3. TimeZoneInfo

> The only "issue" I currently see with it, is that it returns the Cronos parsed CronExpression and not the "input" CronExpression,

If you take `job.CronExpression?.ToString()` you should have the original cron expression, not? That is what we are utilizing in `TryGetSchedule`.

But my take-away is the the current API is good "enough" once we add the `GetAllSchedules` function.

**Comment by linkdotnet** [comment]
@falvarez1 if we offer a `GetAllSchedules` I am not sure if we should name the returning type `Schedule`!?
```csharp
IReadOnlyCollection<Schedule> GetAllSchedules();
```

This might clash with internal things at some point. `UserSchedule`/ `ScheduleInformation` sounds also shady.

**Comment by linkdotnet** [comment]
> I have a small scenario here:

As far as I can tell you are only accessing public information, which makes me believe that your scenario is totally possible in your user code as an extension.

**Comment by KorsG** [comment]
> But my take-away is the the current API is good "enough" once we add the GetAllSchedules function.

Agreed 🙂


> If you take job.CronExpression?.ToString() you should have the original cron expression, not? That is what we are utilizing in TryGetSchedule.

Here's an example of how the Cron becomes different after being parsed into the Cronos CronExpression and using ToString() on that:
![image](https://github.com/NCronJob-Dev/NCronJob/assets/1583564/9d7232ab-9179-4d58-b0e7-103f1bd771c8)

`TryGetSchedule` should behave similarly, if you agree that it should be changed to return the input Cron.

**Comment by linkdotnet** [comment]
> > But my take-away is the the current API is good "enough" once we add the GetAllSchedules function.
> 
> Agreed 🙂
> 
> > If you take job.CronExpression?.ToString() you should have the original cron expression, not? That is what we are utilizing in TryGetSchedule.
> 
> Here's an example of how the Cron becomes different after being parsed into the Cronos CronExpression and using ToString() on that: ![image](https://private-user-images.githubusercontent.com/1583564/337231863-9d7232ab-9179-4d58-b0e7-103f1bd771c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzE1MTEsIm5iZiI6MTcxNzY3MTIxMSwicGF0aCI6Ii8xNTgzNTY0LzMzNzIzMTg2My05ZDcyMzJhYi05MTc5LTRkNTgtYjBlNy0xMDNmMWJkNzcxYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTA1MzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc0MDJjZDY4MzdmNGExZjAwNDQ2ZmU5M2NlNTE5MDhmYWU4MzMwYjlmZTQ4NGY1YmMwMzg5Yzg2ZjFlZDIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lu0XWPUQlflVY6gOxN2-A4akD8GH8Y-bMCZjFdzyFko)
> 
> `TryGetSchedule` should behave similarly, if you agree that it should be changed to return the input Cron.

Ahh thanks for the hint. Yes that is ugly. I will have a look.

**Comment by linkdotnet** [comment]
Now, there is a [`2.7.6`](https://www.nuget.org/packages/NCronJob/2.7.6-preview) prerelease that should address all of your suggestions:
 1. `GetAllRecurringJobs` that retrieves you exactly that list with Jobname, type and so on.
 2. The CRON Expresson returned (also for `Try`) will be the user provided on

**Comment by KorsG** [comment]
Fantastic! I really appreciate all the effort you put into this 🙂

**Comment by harrison314** [comment]
Hello, I'm trying nuget version `2.7.6-preview`, because in my application I need to add cron jobs only in runtime (same job type, different parameter and cron expression).

But call `IRuntimeJobRegistry.AddJob` has no efect.

```
string cronExpression = "*/2 * * * *";
string name = "CronJob_1";

runtimeJobRegistry.AddJob(builder =>
{
            builder.AddJob<CronTriggerJob>(opt => opt.WithCronExpression(cronExpression)
                .WithName(name)
                .WithParameter(name));
});

        var collection =  this.runtimeJobRegistry.GetAllRecurringJobs(); //collection is empty and CronTriggerJob can not executed.
```

**Comment by linkdotnet** [comment]
Hmmm, troublesome :D @harrison314 Thanks for reporting. I will have a look into it.

**Comment by linkdotnet** [comment]
But good that it's still in preview :D

**Comment by linkdotnet** [comment]
@harrison314 Can you show me your `AddNCronJob` part in the `Program.cs`?

**Comment by harrison314** [comment]
>@harrison314 Can you show me your AddNCronJob part in the Program.cs?

```
 builder.Services.AddTransient<CronTriggerJob>(); // Is it necessary to register a Job in DI?
 builder.Services.AddNCronJob();
```

I also tried registering a dummy job at startup, but it behaves the same.

**Comment by linkdotnet** [comment]
You can and should utilize the `AddNCronJob` function itself. 
```csharp
builder.Services.AddNCronJob(s => s.AddJob<CronTriggerJob>());
```

We have an open PR that would even lighten up that requirement. But the general flow is that you don't have to register those jobs yourself. Let the library do the dirty work.

Indepdently there seems to be a bug with `GetAllRecurringJobs`.

**Comment by linkdotnet** [comment]
That said - in your case you might not even need the runtime feature at all. Or is there a reason not to do your call inside `AddNCronJob`?

**Comment by harrison314** [comment]
> Or is there a reason not to do your call inside AddNCronJob?

Yes, there is. I implement alerting/scheduling tasks for a my prototype timeseries database. The database user defines the JS code, cron expression and task name only in the runtime via the REST API. I want every user to be able to have an unlimited number of sheduling tasks.

**Comment by linkdotnet** [comment]
But independent of that, there was really a bug and a missing bit here. I will push a fix and make a new pre-release.

**Comment by linkdotnet** [comment]
> > Or is there a reason not to do your call inside AddNCronJob?
> 
> Yes, there is. I implement alerting/scheduling tasks for a my prototype timeseries database. The database user defines the JS code, cron expression and task name only in the runtime via the REST API. I want every user to be able to have an unlimited number of sheduling tasks.

Yeah that is a perfectly fine case.

In the current state I advise to register the job like this:
```csharp
builder.Services.AddNCronJob(b => b.AddJob<CronTriggerJob>());

// Later in your code:
registry.AddJob(s => s.AddJob<CronTriggerJob>(t => t.WithCronExpression("* * * * *").WithName("My Name")));
```

I will make a nugget deployment soon - there should be a `2.7.7-preview` available in a few minutes. Thanks for reporting!

**Comment by harrison314** [comment]
Thanks, I'll try and give feedback.

**Comment by linkdotnet** [comment]
2.7.7-preview: https://www.nuget.org/packages/NCronJob/2.7.7-preview

As a heads up, we are working on a dashboard and a webAPI to enable your case to be out of the box.
But no ETA at this moment as we have to tackle some other fundamental things first (better observability and so on).

**Comment by harrison314** [comment]
> 2.7.7-preview

Problem still continues.

I used the equivalent of this code:
```
builder.Services.AddNCronJob(b => b.AddJob<CronTriggerJob>());
....
runtimeJobRegistry.AddJob(s => s.AddJob<CronTriggerJob>(t => t.WithCronExpression("* * * * *").WithName("My Name")));
```
I also connect watch from `runtimeJobRegistry` after call `AddJob`:

![obrázok](https://github.com/NCronJob-Dev/NCronJob/assets/12501763/f23c6c4b-e086-4c5b-8131-e3156b2a6409)

If it helps, tomorrow I can make an app to reproduce the problem using the Minimal API.

**Comment by linkdotnet** [comment]
2.7.8: https://www.nuget.org/packages/NCronJob/2.7.8-preview

**Comment by harrison314** [comment]
Thanks, version 2.7.8 fixed it. Adding multiple jobs and deleting them in runtime works correctly.

**Comment by linkdotnet** [comment]
Sorry for the long delay. We did some other stuff in parallel, which needed a complete rewrite of this feature.
We aim to merge the PR soon and hand out a release.

There is a [`2.7.9-preview`](https://www.nuget.org/packages/NCronJob/2.7.9-preview) package available. In theory it isn't anything new, but it would be awesome if someone could try it out and report back.
